# This workflow will build a Java project with M
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Mavens

on:
  push:
    branches: [ dev ]
defaults:
  run:
   working-directory: ./buyGPS

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: cd ~/actions-runner/deploy/buyGps/buyGps/buyGPS
    - run: sudo docker container stop buyGps-container || true
    - run: sudo docker container stop postgres-container || true
    - run: sudo docker container rm buyGps-container || true
    - run: sudo docker image rm gps || true
    - run: sudo docker build -t gps .
    - run: sudo docker container start postgres-container||sudo docker run --name postgres-container -e POSTGRES_PASSWORD=postgres -d postgres:alpine  
    - run: sudo docker run --name buyGps-container -p 8080:8080  --line postgres-container:postgres gps | echo "success"
    
